# Generated by Django 4.2.6 on 2023-11-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.TextField(blank=True, help_text='Введите сведения об авторе', null=True, verbose_name='Сведения об авторе'),
        ),
    ]
