# Generated by Django 4.2.6 on 2023-11-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_author_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='surname',
            field=models.CharField(blank=True, help_text='Введите отчество автора(если есть)', max_length=100, null=True, verbose_name='Фамилия отчество'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, help_text='Вставте изображение обложки книги', null=True, upload_to='images', verbose_name='Изображение обложки'),
        ),
    ]
